### ISSUE TITLE
Music folder is visible but mp3's are not showing..

### ISSUE THREAD

**Issue by siri-guru-mat** [airsonic/airsonic.github.io#42]
at  org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)  ~[spring-web-4.3.25.RELEASE.jar!/:4.3.25.RELEASE]
--
at  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)  ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)  ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199) ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at  org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)  ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81) ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87) ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:609) ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at  org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)  ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1623) ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-8.5.51.jar!/:8.5.51]
at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
&nbsp;
2021-06-16 19:17:51.256  INFO --- o.a.p.service.PodcastService             : Starting scheduled Podcast refresh.
2021-06-16 19:17:51.257  INFO --- o.a.p.service.PodcastService             : Completed scheduled Podcast refresh.
2021-06-17 03:00:00.712  INFO --- o.a.p.s.MediaScannerService              : Starting to scan media library.
2021-06-17 03:00:00.792  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 8 entries.
2021-06-17 03:00:00.792  INFO --- o.a.p.s.MediaScannerService              : Marking non-present files.
2021-06-17 03:00:00.792  INFO --- o.a.p.s.MediaScannerService              : Marking non-present artists.
2021-06-17 03:00:00.793  INFO --- o.a.p.s.MediaScannerService              : Marking non-present albums.
2021-06-17 03:00:00.794  INFO --- o.a.p.s.MediaScannerService              : Completed media library scan.
2021-06-17 03:00:01.740  INFO --- o.a.p.service.PlaylistService            : Starting playlist import.
2021-06-17 03:00:01.741  INFO --- o.a.p.service.PlaylistService            : Completed playlist import.
2021-06-17 19:17:51.256  INFO --- o.a.p.service.PodcastService             : Starting scheduled Podcast refresh.
2021-06-17 19:17:51.294  INFO --- o.a.p.service.PodcastService             : Completed scheduled Podcast refresh.
2021-06-18 03:00:00.709  INFO --- o.a.p.s.MediaScannerService              : Starting to scan media library.
2021-06-18 03:00:00.791  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 8 entries.
2021-06-18 03:00:00.791  INFO --- o.a.p.s.MediaScannerService              : Marking non-present files.
2021-06-18 03:00:00.792  INFO --- o.a.p.s.MediaScannerService              : Marking non-present artists.
2021-06-18 03:00:00.793  INFO --- o.a.p.s.MediaScannerService              : Marking non-present albums.
2021-06-18 03:00:00.793  INFO --- o.a.p.s.MediaScannerService              : Completed media library scan.
2021-06-18 03:00:01.805  INFO --- o.a.p.service.PlaylistService            : Starting playlist import.
2021-06-18 03:00:01.807  INFO --- o.a.p.service.PlaylistService            : Completed playlist import.
2021-06-18 19:17:51.256  INFO --- o.a.p.service.PodcastService             : Starting scheduled Podcast refresh.
2021-06-18 19:17:51.266  INFO --- o.a.p.service.PodcastService             : Completed scheduled Podcast refresh.
2021-06-19 03:00:00.715  INFO --- o.a.p.s.MediaScannerService              : Starting to scan media library.
2021-06-19 03:00:00.891  INFO --- o.a.p.s.MediaScannerService              : Scanned media library with 8 entries.
2021-06-19 03:00:00.891  INFO --- o.a.p.s.MediaScannerService              : Marking non-present files.
2021-06-19 03:00:00.892  INFO --- o.a.p.s.MediaScannerService              : Marking non-present artists.
2021-06-19 03:00:00.893  INFO --- o.a.p.s.MediaScannerService              : Marking non-present albums.
2021-06-19 03:00:00.894  INFO --- o.a.p.s.MediaScannerService              : Completed media library scan.
2021-06-19 03:00:01.739  INFO --- o.a.p.service.PlaylistService            : Starting playlist import.
2021-06-19 03:00:01.741  INFO --- o.a.p.service.PlaylistService            : Completed playlist import.

**Comment by siri-guru-mat** [comment]
Issue fixed - I removed the spaces in the filenames and put them in a directory behind the folder structure, then everything showed up in the list.
